### ISSUE TITLE
Should this plugin still be working?

### ISSUE THREAD

**Issue by maxfrigge** [mcguffin/polylang-fix-relationships#1]
Currently it doesn't fix anything for my.

I am running ACF Pro and use it to set custom taxonomies on custom post types using the relations widget. No matter what I do or how I create the translation.. the relations are lost.

**Comment by mcguffin** [comment]
Main purpose is to keep track of (ACF implemented) post to post connections, like post object field, media, post thumbnail, ... taxonomies are not involved.
All affected ACF types in the highlighted line: https://github.com/mcguffin/polylang-fix-relationships/blob/master/include/class-PolylangPostClonerWatchMeta.php#L9). 
The clone post feature will copy a post and change all connected post objects (and posts parent) to their corresponding translations if existing. The fix relationships feature will do pretty much the same, just without the cloning part. 

(I mainly made this plugin for a client project, sharing it in the hope of being useful to others, that's why documentation is so scarce...)

**Comment by maxfrigge** [comment]
Guess it won't fit into my project then :)

Thanks for sharing!
