### ISSUE TITLE
Compatibility with ACF 5.3.1

### ISSUE THREAD

**Issue by ghost** [mcguffin/polylang-fix-relationships#2]
Hi mcguffin,
I guess that this PlugIn could save my a*. :)
I'm using Polylang as well as ACF and if I choose a relationship (to another post type) in an original post and then add a translation through Polylang, the relationship field is not able to load the posts of the other post type. That is really annoying and as far as I see, this is going to fix it. But also after installing it, I do have the same issue.
Is it already compatible with the latest version?

Thank you very much for your work!

Best,

Philipp

**Comment by mcguffin** [comment]
Hi Phillip, 
what you describe sounds very much like a polylang problem. When ACF loads the post into the dropdown, polylang filters them by the admin-language instead of the post language. 
Do the connected post types occur when you set the admin language (in the admin bar) to the same language as the post you're editing? 
If the answer is yes, the fix you need is here: https://gist.github.com/mcguffin/333a97bf88cc86997e6f

(The Fix Relationships plugin implements a deep-cloning and rewrites post-2-post connections to their translation, so this is something else.)

cheers,
jörn
