### ISSUE TITLE
Can't figure out how to get this working on my WordPress site

### ISSUE THREAD

**Issue by romulo-rocha** [mcguffin/polylang-fix-relationships#4]
Hi! I'd like to use this plugin because I am facing an issue with Polylang and ACF Relation fields, but I don't really know how to get this working with my WordPress project. Is there a tutorial or quick tips on how to use this plugin?

Thanks in advance

**Comment by mcguffin** [comment]
Hi, 
I discontinued this plugin, and just keep it for historical reasons.
It was supposed to work out of the box once, syncing relationships between posts, so that always posts of the same language are assigned to each other.

You might like to take a look on this project, which might receive some maintenance from time to time: https://github.com/mcguffin/polylang-sync
